[project]
name = "mcp-maths-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "miniProjectsauravsatyam27", email = "ss.sauravsatyam@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=4.0.10",
]

[project.scripts]
mcp-maths-server = "mcp_maths_server:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
