[project]
name = "mcp-yt-clinent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "miniProjectsauravsatyam27", email = "ss.sauravsatyam@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "langchain-mcp-adapters>=0.3.1",
    "mcp>=1.28,<2",
    "python-dotenv>=1.2.3",
    "streamlit>=1.64.0",
]

[project.scripts]
mcp-yt-clinent = "mcp_yt_clinent:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
